/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { GovernerContract__factory } from "./GovernerContract__factory";
export { TimeLock__factory } from "./TimeLock__factory";
