/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as nftSol from "./nft.sol";
export * as sosxDaoSol from "./sosxDAO.sol";
export { GovernerContract__factory } from "./GovernerContract__factory";
export { TimeLock__factory } from "./TimeLock__factory";
