/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { GovernorCompatibilityBravoUpgradeable } from "./GovernorCompatibilityBravoUpgradeable";
export type { IGovernorCompatibilityBravoUpgradeable } from "./IGovernorCompatibilityBravoUpgradeable";
