/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { GovernorCompatibilityBravoUpgradeable__factory } from "./GovernorCompatibilityBravoUpgradeable__factory";
export { IGovernorCompatibilityBravoUpgradeable__factory } from "./IGovernorCompatibilityBravoUpgradeable__factory";
