/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as nftSol from "./nft.sol";
export type { nftSol };
import type * as sosxDaoSol from "./sosxDAO.sol";
export type { sosxDaoSol };
export type { GovernerContract } from "./GovernerContract";
export type { TimeLock } from "./TimeLock";
