/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { GovernerContract__factory } from "./GovernerContract__factory";
export { SosxChallenge__factory } from "./SosxChallenge__factory";
