/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { GovernerContract } from "./GovernerContract";
export type { SosxChallenge } from "./SosxChallenge";
